language: java
jdk: oraclejdk8
install: true
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: npbem5UiZrJ5vq5hlkAvFcC3UL4EiiFqMyYMEhX4guDWaqvKDBVEojPOjuZ7e1mbujag6vu8GhmoGmbW0735moR9IHAZNdrNZRI/JR2lQ5yOiVfCVh9mycYmsdNbeEH7+lP0nCURyN0Eiwcq/GBtGzVLzSNTSKtgIk1H4dTBt2XjCthmt3/3uDAITu2gl4Fafg+ncHl3iPK/Mzr4ljh+qavAgfQUqQn23djdhpAZ03ngu6OOzEUpuCJYJXN5JdLYmxLpKwl5UHKOEyYmRoAZ9Y6Fazhg543Hs8l4Krw7NhTOawM/xSexfluSREmqdFMjDPjtB2BnzMx86s9U+eze4A5UW8uUw0DZg2sngVOWhAh158stYIo3CDpJsNuRzOZyO93TmFoeAwIzolUQuH6nixE1k+LpOEHVhqjK+tTOZeutBZ5jGCdS3YrUQfnAbhejnvN53UAbrcWg8lm3yJoBEVAmI5IumU5SjxGHF5dyianurIubI/VeC3aIRwaoMEurD9k4wAvGJ9NSgoOeVxCIAatsIYhc1dymnG8pkwYK/6YOHRTr8hrIu1anhh83K0Da0TINFd0/Dq0TgmkcIOvWmlxwivMWwiG2JQGm97uQYhuzNMbVbDycpFsZffBRo5M8z+Ofbjq52+4R00R1Tl2ekBi4p5ByN6Le2Yfk6cvslhY=
